### ISSUE TITLE
Dead links in list of articles

### ISSUE THREAD

**Issue by CharlesGaydon** [LyonDataViz/teaching#1]
On this [page](https://lyondataviz.github.io/teaching/lyon1-m2/2017/articles.html), links of some articles are dead. Among them :
Graphes : 

- Exploring the Design Space of Interactive Link Curvature in Network Diagrams
- Visualizing Network Data

Données multi-dimensionnelles :
- VisDB: a system for visualizing large databases
- Quality Metrics in High-Dimensional Data Visualization: An Overview and Systematization
Graphes

**Comment by aurelient** [comment]
Thanks for the report. The links should be fixed now.
https://github.com/LyonDataViz/teaching/commit/14f3ca85e03b421ed64558a28733e5ae6b13e006
