### ISSUE TITLE
Lien vers les sides du prochain cours non actualisé

### ISSUE THREAD

**Issue by CharlesGaydon** [LyonDataViz/teaching#2]
Sur cette [page](https://lyondataviz.github.io/teaching/lyon1-m2/2017/) encore,  le lien vers le cours "Principes de programmation en D3.js" n'y mène pas. Est-il possible de l'actualiser pour pouvoir se préparer un peu à D3.js ?
Merci !

**Comment by aurelient** [comment]
Bonjour, 
c'est normal, ce cours est nouveau et pas encore terminé, le lien sera corrigé avant le cours par @romsson 

Quelques pointeurs en attendant : 
Introduction à D3.js (Vadim Ogievetsky, co-créateur de D3.js) :
http://vadim.ogievetsky.com/IntroD3/#1
3 little circles:
https://bost.ocks.org/mike/circles/
Ressources en ligne :
https://github.com/arnicas/d3-faq
https://github.com/arnicas/interactive-vis-course
